import { Project, Experience, NavItem } from './types';

export const NAV_ITEMS: NavItem[] = [
  { label: '// HOME', href: '#hero' },
  { label: '// ABOUT', href: '#about' },
  { label: '// PROJECTS', href: '#projects' },
  { label: '// EXPERIENCE', href: '#experience' },
  { label: '// CONTACT', href: '#contact' },
];

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'AI Resume Analyzer',
    description: 'An intelligent resume analyzer built with React Router featuring server-side rendering, HMR, and TailwindCSS for modern UI styling.',
    techStack: ['React', 'TypeScript', 'Vite', 'TailwindCSS', 'Docker'],
    imageUrl: 'https://picsum.photos/600/400?random=1',
    githubUrl: 'https://github.com/omsatote/ai-resume',
    category: 'AI',
    problem: 'Manual resume screening is time-consuming and prone to human bias.',
    solution: 'Built an AI-powered analyzer with React Router SSR for fast, intelligent resume parsing.',
  },
  {
    id: '2',
    title: 'Portfolio Website v2.0',
    description: 'A modern, responsive portfolio website showcasing projects and skills with multi-page layout and React-Bootstrap styling.',
    techStack: ['React.js', 'Node.js', 'Express.js', 'CSS3', 'Vercel'],
    imageUrl: 'https://picsum.photos/600/400?random=2',
    githubUrl: 'https://github.com/omsatote/portfolio.omsatote',
    category: 'Portfolio',
    problem: 'Needed a professional online presence to showcase skills and projects.',
    solution: 'Created a responsive multi-page portfolio with React and deployed on Vercel.',
  },
  {
    id: '3',
    title: 'Script Chatbot',
    description: 'An interactive chatbot website with services, contact, and about pages built with HTML, SCSS, and JavaScript.',
    techStack: ['HTML', 'SCSS', 'CSS', 'JavaScript'],
    imageUrl: 'https://picsum.photos/600/400?random=3',
    githubUrl: 'https://github.com/omsatote/scriptchatbot',
    category: 'Chatbot',
    problem: 'Users needed an interactive way to get scripted responses and information.',
    solution: 'Developed a chatbot interface with multiple pages for services and contact.',
  },
  {
    id: '4',
    title: 'Song Chatbot',
    description: 'A music-themed chatbot interface for discovering and interacting with song recommendations.',
    techStack: ['HTML', 'CSS', 'JavaScript'],
    imageUrl: 'https://picsum.photos/600/400?random=4',
    githubUrl: 'https://github.com/omsatote/songchatbot',
    category: 'Chatbot',
    problem: 'Music discovery can be overwhelming without personalized guidance.',
    solution: 'Built an interactive chatbot that helps users discover songs through conversation.',
  },
  {
    id: '5',
    title: 'Om Gulab',
    description: 'A personal web development project showcasing programming fundamentals and web development skills.',
    techStack: ['HTML', 'CSS', 'JavaScript'],
    imageUrl: 'https://picsum.photos/600/400?random=5',
    githubUrl: 'https://github.com/omsatote/omgulab',
    category: 'Web',
    problem: 'Wanted to practice and demonstrate core web development fundamentals.',
    solution: 'Created a clean web project applying HTML, CSS, and JavaScript best practices.',
  },
  {
    id: '6',
    title: 'Hacktoberfest 2025 Contribution',
    description: 'Open source contributions to Hacktoberfest 2025 featuring valuable code contributions using Jupyter Notebook.',
    techStack: ['Jupyter Notebook', 'Python', 'Open Source'],
    imageUrl: 'https://picsum.photos/600/400?random=6',
    githubUrl: 'https://github.com/omsatote/Hacktoberfest2025-Open-source-',
    category: 'Data',
    problem: 'Open source community needs more contributors and quality code.',
    solution: 'Contributed Python notebooks and code during Hacktoberfest 2025.',
  },
];

export const EXPERIENCE: Experience[] = [
  {
    id: '1',
    role: 'Self-Taught Developer',
    company: 'Personal Development',
    date: '2024 - Present',
    description: 'Learning web development fundamentals, building chatbots, and creating portfolio projects using modern technologies.',
    skills: ['React', 'TypeScript', 'Node.js', 'Python'],
  },
  {
    id: '2',
    role: 'Frontend Developer Intern',
    company: 'Bluestock',
    date: '2025 - Present',
    description: 'Developing responsive user interfaces and interactive web components for fintech applications.',
    skills: ['React', 'JavaScript', 'CSS', 'HTML'],
  },
  {
    id: '3',
    role: 'Open Source Contributor',
    company: 'Hacktoberfest 2025',
    date: '2024 - Present',
    description: 'Actively contributing to open source projects, participating in Hacktoberfest 2025, and collaborating with the global developer community.',
    skills: ['Python', 'Jupyter', 'Git', 'Open Source'],
  },
];